// Manifest for the "New Board" templates section (docs/specs/26-board-templates.md).
// Each entry's actual document data lives in a real project file — the app's own
// ProjectFileV1 format (src/application/document/projectFile.ts) — under
// public/board-templates/<id>.json, generated by scripts/generateBoardTemplates.mjs
// from reference art in .tmp/patterns/*.svg (scratch, not committed). Fetched on
// demand when a card is clicked, not bundled — see BoardSetup.tsx.
export interface BoardTemplate {
  id: string;
  nameKey: string;
  url: string;
}

export const BOARD_TEMPLATES: BoardTemplate[] = [
  { id: "spiral", nameKey: "spiral", url: "/board-templates/spiral.json" },
  { id: "comet", nameKey: "comet", url: "/board-templates/comet.json" },
  { id: "flower", nameKey: "flower", url: "/board-templates/flower.json" },
  { id: "lotus", nameKey: "lotus", url: "/board-templates/lotus.json" },
  { id: "sun", nameKey: "sun", url: "/board-templates/sun.json" },
  { id: "star-of-david", nameKey: "starOfDavid", url: "/board-templates/star-of-david.json" },
  { id: "spirals", nameKey: "spirals", url: "/board-templates/spirals.json" },
  { id: "assymetry", nameKey: "assymetry", url: "/board-templates/assymetry.json" },
  { id: "polygon", nameKey: "polygon", url: "/board-templates/polygon.json" },
];
